set nocompatible
filetype off

execute pathogen#infect()
set sessionoptions-=options

syntax on
filetype plugin indent on
syntax enable
set background=dark
colorscheme myrailscasts
" colorscheme codeschool
set number
set tabstop=2 shiftwidth=2 expandtab
set ai
set smartindent
set smarttab
set expandtab
set nowrap
set noswapfile
set nobackup
set noerrorbells visualbell t_vb=

